import fs from "node:fs/promises";
import path from "node:path";

const ROOT = process.cwd();
const OUTPUT_DIR = path.join(ROOT, "docs");
const OUTPUT_FILE = path.join(OUTPUT_DIR, "PROJECT_DOCUMENTATION.generated.md");

const SECTIONS = [
  ["Components", path.join(ROOT, "src", "components")],
  ["Pages", path.join(ROOT, "src", "pages")],
  ["Routes", path.join(ROOT, "src", "routes")],
  ["Hooks", path.join(ROOT, "src", "hooks")],
  ["Utilities", path.join(ROOT, "src", "utils")],
];

function normalizeProp(prop) {
  return prop
    .replace(/\s*=.*$/, "")
    .replace(/^\.\.\./, "")
    .trim();
}

function extractProps(source) {
  const match = source.match(
    /export\s+default\s+function\s+\w+\s*\(\s*\{([\s\S]*?)\}\s*\)/
  );
  if (!match) return [];

  return match[1]
    .split(",")
    .map(normalizeProp)
    .filter(Boolean);
}

function extractHooks(source) {
  return Array.from(new Set(source.match(/\buse[A-Z][A-Za-z0-9_]*/g) || []));
}

function extractImports(source) {
  return Array.from(
    source.matchAll(/import\s+.+?\s+from\s+"([^"]+)";/g),
    (match) => match[1]
  );
}

function extractDefaultExportName(source, fileName) {
  const match = source.match(/export\s+default\s+function\s+([A-Za-z0-9_]+)/);
  return match ? match[1] : fileName.replace(/\.[^.]+$/, "");
}

async function buildSection(title, dirPath) {
  const fileNames = (await fs.readdir(dirPath)).filter((fileName) =>
    /\.(js|jsx)$/.test(fileName)
  );

  const entries = await Promise.all(
    fileNames.map(async (fileName) => {
      const fullPath = path.join(dirPath, fileName);
      const source = await fs.readFile(fullPath, "utf8");
      return {
        fileName,
        name: extractDefaultExportName(source, fileName),
        props: extractProps(source),
        imports: extractImports(source),
        hooks: extractHooks(source),
        lines: source.split(/\r?\n/).length,
      };
    })
  );

  const sorted = entries.sort((a, b) => a.name.localeCompare(b.name));
  const body = sorted
    .map((entry) => {
      const props = entry.props.length ? entry.props.join(", ") : "none";
      const hooks = entry.hooks.length ? entry.hooks.join(", ") : "none";
      const imports = entry.imports.length ? entry.imports.join(", ") : "none";

      return [
        `### ${entry.name}`,
        `- File: \`${path.relative(ROOT, path.join(dirPath, entry.fileName))}\``,
        `- Props / parameters: ${props}`,
        `- Hooks / helpers: ${hooks}`,
        `- Direct imports: ${imports}`,
        `- Approx. size: ${entry.lines} lines`,
      ].join("\n");
    })
    .join("\n\n");

  return `## ${title}\n\n${body}`;
}

async function main() {
  await fs.mkdir(OUTPUT_DIR, { recursive: true });

  const sections = [];
  for (const [title, dirPath] of SECTIONS) {
    sections.push(await buildSection(title, dirPath));
  }

  const content = [
    "# Project Documentation",
    "",
    "This file is generated by `npm run docs:generate`.",
    "",
    "- Project: Word Search",
    "- Started: 2025",
    `- Generated at: ${new Date().toISOString()}`,
    "",
    "## Overview",
    "",
    "The project is a browser-based word search game built with React, Redux Toolkit, React Router and Vite. It persists player information, game history, settings and GDPR cookie consent locally in the browser.",
    "",
    ...sections,
    "",
    "## Generated Notes",
    "",
    "- Components are documented from their exported function signatures and imports.",
    "- Files without component props still appear so the structure remains auditable.",
  ].join("\n");

  await fs.writeFile(OUTPUT_FILE, content, "utf8");
  console.log(`Generated documentation: ${path.relative(ROOT, OUTPUT_FILE)}`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
